inline int64_t unpack_long(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline int8_t unpack_tinyint(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline int32_t unpack_int(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline float unpack_float(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline double unpack_double(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline int unpack_short_nocroak(pTHX_ char *input, STRLEN len, STRLEN *pos, uint16_t *out);
inline uint16_t unpack_short(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline int unpack_short_bytes(pTHX_ char *input, STRLEN len, STRLEN *pos, char **output, STRLEN *outlen);
inline int unpack_bytes(pTHX_ char *input, STRLEN len, STRLEN *pos, char **output, STRLEN *outlen);
SV *unpack_bytes_sv(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline int unpack_string_nocroak(pTHX_ char *input, STRLEN len, STRLEN *pos, char **output, STRLEN *outlen);
inline void unpack_string(pTHX_ char *input, STRLEN len, STRLEN *pos, char **output, STRLEN *outlen);
SV *unpack_string_sv(pTHX_ char *input, STRLEN len, STRLEN *pos);
inline void unpack_long_string(pTHX_ char *input, STRLEN len, STRLEN *pos, char **output, STRLEN *outlen);
